### PR TITLE
fix: Introduced a class to select colors

### PR DESCRIPTION
**Pull request by AyushChakraborty**
created a class called Color which has two
class methods to introduce two new themes, will
work more on it later

### CODE REVIEW

**Comment by AyushChakraborty** [comment]
@NavneetNayak kindly chk the same

**Comment by NavneetNayak** [comment]
@AyushChakraborty There is an error look into this
image
I will formally assign you this issue now make sure you are not assigned any other issues

**Comment by AyushChakraborty** [comment]
@NavneetNayak i am assigned to no other issue now

**Comment by AyushChakraborty** [comment]
assign me this now

**Comment by AyushChakraborty** [comment]
@NavneetNayak pls chk it now, updated it

**Comment by NavneetNayak** [comment]
@AyushChakraborty pls continue working on it, you need to propose a way to change themes and allow the user to include their own themes

**Comment by AyushChakraborty** [comment]
@NavneetNayak kindly chk now, added two buttons from which users can choose

**Comment by AyushChakraborty** [comment]
will work on adding new themes now

**Comment by NavneetNayak** [comment]
@AyushChakraborty ok I will extend your timer
image
pls continue working on it and fixing

**Comment by AyushChakraborty** [comment]
ok will do

**Comment by AyushChakraborty** [comment]
@NavneetNayak added some functionality where the buttons appear eveytime after refresh and also such that the users can only change the color once per typing session, will implement the custom color chooser now

**Comment by NavneetNayak** [comment]
@AyushChakraborty  cool keep working on it would be great if you can beautify it

**Comment by AyushChakraborty** [comment]
@NavneetNayak kk

**Comment by AyushChakraborty** [comment]
@NavneetNayak pls chk now, added all needed functionalities mentioned by the issue, this should be it

**Comment by NavneetNayak** [comment]
@AyushChakraborty can you fix the issue of 
image
the color being in the background of text as well as the text.

**Comment by AyushChakraborty** [comment]
@NavneetNayak  ok will take a look

**Comment by AyushChakraborty** [comment]
@NavneetNayak its actually a stylistic choice as the text element has its background colored in the first color of the two colors provided

**Comment by NavneetNayak** [comment]
@AyushChakraborty  Yep can you just seperate those, that'll be the last thing, I'll assign you points after this

**Comment by AyushChakraborty** [comment]
@NavneetNayak do you mean let the background of the text be the same as the overall background?

**Comment by NavneetNayak** [comment]
@AyushChakraborty yes

**Comment by AyushChakraborty** [comment]
ok will do

**Comment by AyushChakraborty** [comment]
@NavneetNayak its done

**Comment by NavneetNayak** [comment]
!bounty 200

**Comment by NavneetNayak** [comment]
@AyushChakraborty nice good job!

**Comment by AyushChakraborty** [comment]
@NavneetNayak thanks man

**Comment by NavneetNayak** [comment]
!bounty 150

**Comment by AyushChakraborty** [comment]
@NavneetNayak can you explain why the drop in points?

**Pull request closed without merging**
